<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyTitle>TransmutationLearning</AssemblyTitle>
    <Description>Cross-modal classifier development for single-cell proteomics</Description>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SCPBrowser\SCPBrowser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="img\" />
  </ItemGroup>

</Project>
